<?php declare(strict_types=1);

namespace SwagShopFinder\Core\Content\ShopFinder;

use Shopware\Core\Framework\DataAbstractionLayer\EntityDefinition;
use Shopware\Core\Framework\DataAbstractionLayer\Field\FkField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\Flag\PrimaryKey;
use Shopware\Core\Framework\DataAbstractionLayer\Field\Flag\Required;
use Shopware\Core\Framework\DataAbstractionLayer\Field\IdField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\ManyToOneAssociationField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\OneToManyAssociationField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\StringField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\TranslatedField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\TranslationsAssociationField;
use Shopware\Core\Framework\DataAbstractionLayer\FieldCollection;
use Shopware\Core\Framework\DataAbstractionLayer\Field\BoolField;
use Shopware\Core\System\Country\CountryDefinition;
use SwagShopFinder\Core\Content\ShopFinder\Aggregate\SwagShopTranslation\SwagShopFinderTransDefinition;

class SwagShopFinderDefinition extends EntityDefinition
{
    public const ENTITY_NAME = 'swag_shop_finder';

    public function getEntityName(): string
    {
        return self::ENTITY_NAME;
    }

    public function getEntityClass(): string
    {
        return SwagShopFinderEntity::class; // TODO: Change the autogenerated stub
    }
    public function getCollectionClass(): string
    {
        return SwagShopFinderCollection::class; // TODO: Change the autogenerated stub
    }

    protected function defineFields(): FieldCollection
    {
        return new FieldCollection([
            (new IdField('id','id'))->addFlags(new Required(),new PrimaryKey()),
            new BoolField('active','active'),
            (new TranslatedField('name')),
            (new StringField('street','street'))->addFlags(new Required()),
            (new StringField('post_code','postCode'))->addFlags(new Required()),
            (new StringField('city','city'))->addFlags(new Required()),
            new StringField('url','url'),
            new StringField('telephone','telephone'),
            new StringField('open_times','open_times'),

            new FkField('country_id','country_id',CountryDefinition::class),
            //Country
            new ManyToOneAssociationField(
                'country',
                'country_id',
                CountryDefinition::class,
                'id',
                false
            ),
            //Translation
            new TranslationsAssociationField(
                SwagShopFinderTransDefinition::class,
                'swag_shop_finder_id'
            )

        ]
    );
    }
}
