<?php
declare(strict_types=1);

namespace SwagShopFinder\Core\Content\ShopFinder\Aggregate\SwagShopTranslation;

use Shopware\Core\Framework\DataAbstractionLayer\EntityTranslationDefinition;
use Shopware\Core\Framework\DataAbstractionLayer\Field\Flag\Required;
use Shopware\Core\Framework\DataAbstractionLayer\Field\StringField;
use Shopware\Core\Framework\DataAbstractionLayer\FieldCollection;
use SwagShopFinder\Core\Content\ShopFinder\SwagShopFinderDefinition;


class SwagShopFinderTransDefinition extends EntityTranslationDefinition
{
    public const ENTITY_NAME = 'swag_shop_finder_trans';

    public function getEntityName(): string
    {
        return self::ENTITY_NAME;
    }

    public function getEntityClass(): string
    {
            return SwagShopFinderTransEntity::class; // TODO: Change the autogenerated stub
    }
    public function getCollectionClass(): string
    {
        return SwagShopFinderTransCollection::class; // TODO: Change the autogenerated stub
    }
    public function getParentDefinitionClass(): string
    {
        return SwagShopFinderDefinition::class;
    }

    protected function defineFields(): FieldCollection
    {
        return new FieldCollection([
            (new StringField('name', 'name'))->addFlags(new Required()),
        ]);
    }
}
