<?php declare(strict_types=1);

namespace SwagShipFinder\Core\Content\ShipFinder\Aggregate\SwagShipTranslation;

use Shopware\Core\Framework\DataAbstractionLayer\EntityTranslationDefinition;
use Shopware\Core\Framework\DataAbstractionLayer\Field\Flag\Required;
use Shopware\Core\Framework\DataAbstractionLayer\Field\StringField;
use Shopware\Core\Framework\DataAbstractionLayer\FieldCollection;
use SwagShipFinder\Core\Content\ShipFinder\SwagShipFinderDefinition;


class SwagShipFinderTransDefinition extends EntityTranslationDefinition
{
    public const ENTITY_NAME = 'swag_ship_finder_trans';

    public function getEntityName(): string
    {

        return self::ENTITY_NAME;
    }
    public function getEntityClass(): string
    {
        return SwagShipFinderTransEntity::class; // TODO: Change the autogenerated stub
    }

    public function getCollectionClass(): string
    {
        return SwagShipFinderTransCollection::class;
    }

    public function getParentDefinitionClass(): string
    {
        return SwagShipFinderDefinition::class;
    }

    protected function defineFields(): FieldCollection
    {
        return new FieldCollection([
            (new StringField('name', 'name'))->addFlags(new Required()),
            (new StringField('city','city'))->addFlags(new Required())
        ]);
    }
}
